### ISSUE TITLE
OHBM Submission

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#105]
@arokem @KirstieJane @jakevdp @ctoroserey @kdestasio @choldgraf @yarikoptic @andim @rxqx @beckmart @gvwilson @RaginSagan @ilkayisik @PeerHerholz @kristianeschenburg @erramuzpe @mvdoc @mandel01 @andyfaff 

Hi! :smile: 
You are all being linked here because you have provided intellectual contributions to this software through code and/or conversation.
I am submitting an abstract to [OHBM 2019](https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageID=3882&activateFull=true) and I am putting out an open call to all of you to ask if you would like to be an author on the submission. The submission deadline is December 19th (next Wednesday). 

I will send the abstract to anyone here that expresses interest to be an author on the submission, (with the option to revoke if you change your mind after seeing the abstract).

I apologize for the late notice and if you would like to contact me privately, my email is: james-kent@uiowa.edu

Thank you for your time and contributions!

**P.S.**
If you would like to be removed from the `zenodo` file and/or not be contacted in the future about this project, you can say so here or through email and I will remove you.

**Comment by mandel01** [comment]
Please remove me (now and for any future submissions). Best of luck!

**Comment by choldgraf** [comment]
This is pretty far outside of my field of study, but if I can be helpful with high-level comments etc I'm happy to help out!

**Comment by yarikoptic** [comment]
Ah, all the unsung shablona heroes!  Thank you @jdkent for considering me, but my contribution to NiBetaSeries is non existent so I do not deserve the praise (or blame) yet ;)  Please remove me (but who knows -- I might come back).
Cheers!

**Comment by mvdoc** [comment]
Thanks @jdkent for considering me, but my contribution is minimal, so please remove me :)

**Comment by gvwilson** [comment]
Ditto.
Thanks,
Greg

**Comment by KirstieJane** [comment]
Hi @jdkent! Thank you so much for being so incredibly inclusive in your original author list! It really made me happy to see you going as big as possible on who has helped out with the project.

I think I've contributed with a code of conduct and contributing guidelines, right? And I suppose some conversations at Neurohackademy about building up a community?

I'm on the fence about whether that counts as enough of a contribution...but I think in this case it probably doesn't. I'll do what @arokem is doing and use this as a wonderful example of a community driven BIDS app ✨ 👾 

(If there's more that I can do to help out, please let me know!)

**Comment by jdkent** [comment]
Sorry for the long delay, but the submission was completed with your wishes kept in mind, thank you so much for responding, and I may contact some of you in the future for help. 
Thanks!
