### ISSUE TITLE
add link to NiBetaSeries jupyter notebook in README

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#118]
[inspired from this comment](https://github.com/HBClab/NiBetaSeries/issues/92#issuecomment-448241072)
**Is your feature request related to a problem? Please describe.**
NiBetaSeries Tutorial is not immediately salient to new users

**Describe the solution you'd like**
Link NiBetaSeries tutorial to the README

**Describe alternatives you've considered**
N/A

**Additional context**
Place the following sentence (or something similar in the README.rst under the [Documentation](https://github.com/HBClab/NiBetaSeries/blob/master/README.rst#documentation) heading:

>>> You can also checkout the \`NiBetaSeries Tutorial \<https://nibetaseries.readthedocs.io/en/latest/auto_examples/plot_run_nibetaseries.html#sphx-glr-auto-examples-plot-run-nibetaseries-py>`_!

The sentence is formatted with restructured text, in this case I am using an [external hyperlink](http://docutils.sourceforge.net/docs/user/rst/quickref.html#external-hyperlink-targets) to link the tutorial.

P.S. to myself, I should switch to an internal link once I figure out how.

**Update**
use nilearn as reference?
example filename: `sphx_glr_auto_examples_02_decoding_plot_oasis_vbm.py`

mine would be: `sphx_glr_auto_examples_plot_run_nibetaseries.py`

example with internal link:
>>> You can also checkout the \`NiBetaSeries Tutorial \<sphx_glr_auto_examples_plot_run_nibetaseries.py>`_!

**Comment by PeerHerholz** [comment]
Hey @jdkent,

what's the current status on this? 
Should the nilearn version be implemented?

**Comment by jdkent** [comment]
I think the nilearn method should be used, but I'm having trouble finding it in the sphinx-gallery documentation
