### ISSUE TITLE
clarify in demo that you are stripping color codes rather than coordinates

### ISSUE THREAD

**Issue by mwvoss** [HBClab/NiBetaSeries#123]
v 0.2.3

clarify in demo that you are stripping color codes rather than coordinates in this section of the tutorial:
https://nibetaseries.readthedocs.io/en/latest/auto_examples/plot_run_nibetaseries.html#manipulate-the-region-order-file

**Comment by jdkent** [comment]
specifically `drop coordinate columns` should become `drop color codes` in [this section](https://github.com/HBClab/NiBetaSeries/blob/19655d90673a559ebd099b8194675833fce82303/examples/plot_run_nibetaseries.py#L133)
