### ISSUE TITLE
Make Tutorial Simpler/Clearer

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#125]
[original comment](https://github.com/openjournals/joss-reviews/issues/1295#issuecomment-477289593)

> I'm a little bit unsure about the Jupyter Notebook-style tutorial walkthrough in the "How to run" documentation. If I was planning to run this, I'd likely be running it from the Linux command line (maybe via a scheduler like Slurm on my server)—not invoking it via Python's subprocess. You jump through a bunch of hoops with Python just to download and modify the example data and only one cell of the tutorial actually runs nibs. I think this material is useful, particularly for users to see how to modify idiosyncratic OpenNeuro datasets, but I'm not sure there's enough focus on the nibs invocation. An alternative approach would be to upload the minimal dataset with all necessary modifications to figshare or something and download that in the tutorial. This would avoid spending so much of the tutorial on data manipulation and spend a few more cells describing the nibs command-line invocation and various options.

**Comment by snastase** [comment]
PR #154 helps a lot; I think this can be closed.

**Comment by jdkent** [comment]
Thanks! Closing.
