### ISSUE TITLE
adaptive configuration of _events.tsvs

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#126]
[original comment](https://github.com/openjournals/joss-reviews/issues/1295#issuecomment-477289593)

> This brings up the point that, if the preprocessed BIDS derivatives (e.g., in *_events.tsv) are fairly standard, should we expect nibs be able to handle them internally? For example, you manually rename some columns and reassign "Yes/No" values to 1 and 0 to satisfy assumptions. Another approach to this would be to build in some optional arguments in the nibs CLI that allows the user to specify column names and acceptable value names (and map to numerical values if need be). For example, when I run nibs, I might have a command-line argument specifying that conditions is the column name indicating trial types and that it should have three possible conditions values (neutral, congruent, and incongruent), and another argument that specifying the correct column and mapping {'Yes': 1, 'No': 0}. I'm not necessarily saying this should be the way things are, just offering this an alternative approach. I'm genuinely curious if this would be feasible and if it's better or worse in terms of software design.

**Comment by jdkent** [comment]
For the example you gave, (`Yes/No`) to (1/0), I do not believe that was strictly necessary, and I can remove that step from the notebook. In general however, I am more inclined to try to have a faithful representation of the [bids specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html) and not provide flexibility beyond what the specification allows.

**Comment by snastase** [comment]
> For the example you gave, (`Yes/No`) to (1/0), I do not believe that was strictly necessary, and I can remove that step from the notebook. In general however, I am more inclined to try to have a faithful representation of the [bids specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html) and not provide flexibility beyond what the specification allows.

Makes sense to me—can close this issue.
