### ISSUE TITLE
clarify/update high/low pass filter options

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#130]
> What are the recommendations for high-/low-pass filtering? Is there a precedent in the literature for any recommended values? In fact, the documentation mentions both low- and high-pass filtering, but I only see an option for supplying a low-pass filter in the usage documentation.

**Comment by tsalo** [comment]
I believe that `period_cut` in fact refers to a high-pass filter (per https://github.com/nistats/nistats/issues/318), so the documentation may be incorrect regarding the filter. The newest version of nistats has also replaced `period_cut` with `high_pass`, and the only associated change to the actual values is moving from seconds to Hz.

**Comment by jdkent** [comment]
Thanks for catching this, since nistats has not had any "official" releases since that fix, we will have to pin nistats to a specific commit, if there is not a preference, I would probably just do the most recent commit, and make the necessary underlying changes to match their current api. Would you like to do this?

**Comment by tsalo** [comment]
Whoops, I didn't realize that they hadn't made a release. I think it would make more sense to use the current release of nistats, but to change usage of `low-pass` (or related) to `high-pass` throughout NiBetaSeries. Then, when nistats makes a release, we can make the relevant changes to the argument for FirstLevelModel and the unit of the filter.

I'd be happy to do it.
