### ISSUE TITLE
Create Pull Request Template

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#19]
sources for motivation
- [fmriprep](https://github.com/poldracklab/fmriprep/blob/master/docs/pull_request_template.md)
- [tedana](https://github.com/ME-ICA/tedana/blob/master/.github/pull_request_template.md)
- [nipype](https://github.com/nipy/nipype/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by ctoroserey** [comment]
I'll take this issue
