### ISSUE TITLE
Add nano to development container

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#194]
**Is your feature request related to a problem? Please describe.**
My default git editor is nano, but it is not installed in the development container

**Describe the solution you'd like**
Install nano in the development container

**Describe alternatives you've considered**
use vscode as the default git editor

**Additional context**

Specifically [this bit in Dockerfile_devel](https://github.com/HBClab/NiBetaSeries/blob/f498a4c724f8f2d2e6d6ad8c40dc8406a06ce6c4/Dockerfile_devel#L7-L11):
```
# net-tools needed for code-server
RUN apt-get update &&\
    apt-get install -y \
        net-tools \
        git
```
should be
```
# net-tools needed for code-server
RUN apt-get update &&\
    apt-get install -y \
        net-tools \
        git \
        nano
```

**Comment by PeerHerholz** [comment]
Hi team,

if no one is on it, I would give it a try.

Best, Peer

**Comment by jdkent** [comment]
@PeerHerholz, thanks for taking this on. Since this issue is pretty straight-forward, I'll give you another challenge if you wish. If you know someone that does not have a lot (or any) experience with github, try and walk them through making this change and help them submit a pull request. Do you have anyone in mind/that would be interested?

If not, of course I appreciate any/all contributions you make.

**Comment by PeerHerholz** [comment]
@jdkent, sorry for the late response. Yeah, you're completely right, that's why I hesitated in the beginning. I'll have a look if I can find someone!

**Comment by PeerHerholz** [comment]
@M-earnest would be up for it.

**Comment by jdkent** [comment]
That's awesome, thanks @PeerHerholz! @M-earnest, would you like a read the [contributing guide](https://nibetaseries.readthedocs.io/en/latest/contributing.html) and make a pull request? I can help answer any questions you have to get started.
