### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#20]
sources for inspiration
- [tedana](https://github.com/ME-ICA/tedana/blob/master/Code_of_Conduct.md)
-

**Comment by KirstieJane** [comment]
🎉🎉🎉 Tag me if you need any help or a review (its important to update the code of conduct for the new project!)

**Comment by jdkent** [comment]
@PeerHerholz That would be great, I'll give this issue to you! Thanks!
