### ISSUE TITLE
Add title to CHANGELOG and change version headings to subheadings

### ISSUE THREAD

**Issue by tsalo** [HBClab/NiBetaSeries#208]
**Is your feature request related to a problem? Please describe.**
The RTD sidebar is cluttered by the changelog. It would be nice if it was an expandable section instead.

**Describe the solution you'd like**
If CHANGELOG.rst is given a title (e.g., CHANGELOG or "What's new") and the versions listed (which are currently headers) are converted to subheaders, then the page will become expandable on the sidebar and in the toctree.

**Describe alternatives you've considered**
I suppose you could keep it as is or drop the changelog from the RTD site, but I think it's useful to have.

**Additional context**
![image](https://user-images.githubusercontent.com/8228902/65254846-e878f180-daca-11e9-9144-02234b2da975.png)

**Comment by jdkent** [comment]
Thanks for reporting this, I agree this should be changed.
