### ISSUE TITLE
singularity pull instructions incorrect

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#214]
**Describe the bug**
the singularity build command in [installation.rst](https://github.com/HBClab/NiBetaSeries/blame/c61ea6bd8d85735e5817cb8984b0fc31900ccd125/docs/installation.rst#L62) says `singularity build /path/to/image/nibetaseries-vX.Y.Z.simg docker://HBClab/nibetaseries:vX.Y.Z`, but HBC in HBClab should be lowercase and look like this:
`singularity build /path/to/image/nibetaseries-vX.Y.Z.simg docker://hbclab/nibetaseries:vX.Y.Z`

the error message: 
```
Docker image path: index.docker.io/HBClab/nibetaseries:v0.3.2
ERROR UNAUTHORIZED: authentication required
ERROR Check existence, naming, and permissions
Cleaning up...
```
**To Reproduce**
type this instruction: `singularity build /path/to/image/nibetaseries-vX.Y.Z.simg docker://HBClab/nibetaseries:vX.Y.Z`

**Expected behavior**
should download the singularity image

**Desktop (please complete the following information):**
N/A

**nibetaseries version**
0.3.2

**Additional context**

change `singularity build /path/to/image/nibetaseries-vX.Y.Z.simg docker://HBClab/nibetaseries:vX.Y.Z`

to 

`singularity build /path/to/image/nibetaseries-vX.Y.Z.simg docker://hbclab/nibetaseries:vX.Y.Z`

in 

[installation.rst](https://github.com/HBClab/NiBetaSeries/blame/c61ea6bd8d85735e5817cb8984b0fc31900ccd125/docs/installation.rst#L62)

**Comment by pranesh-sp** [comment]
Can I take this up or is someone already working on it?

**Comment by jdkent** [comment]
@pranesh-sp, you are good to take this issue on, thank you!

**Comment by pranesh-sp** [comment]
> @pranesh-sp, you are good to take this issue on, thank you!

@jdkent, Thanks!

**Comment by PeerHerholz** [comment]
Hi folks,

just dropping in to ask if there are any updates here?

**Comment by jdkent** [comment]
This has not been fixed yet, so if you want to take it, I would say go ahead. 

As for `docker2singularity`, if you want to add the example, awesome!

**Comment by PeerHerholz** [comment]
Coolio,

just to be sure before I go ahead and work on this: @pranesh-sp did you already work on these changes?

**Comment by PeerHerholz** [comment]
I'll give it a try then.
