### ISSUE TITLE
documentation headers are inconsistent

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#232]
**Describe the bug**
Some of the top level headers (and sub-sections) in the `rst` files use `#####` when they should use `=====` to be consistent. Need to switch `#####` headers with `=====`.

**To Reproduce**
look in [release_instructions.rst}(https://github.com/HBClab/NiBetaSeries/blame/abf1d101a921b05b8eea5aec10de4f7d22666f18/docs/development/release_instructions.rst#L3) and [README.rst](https://github.com/HBClab/NiBetaSeries/blame/abf1d101a921b05b8eea5aec10de4f7d22666f18/README.rst#L3)

**Expected behavior**
all headers using `=====`

**Desktop (please complete the following information):**
N/A

**nibetaseries version**
0.3.2_dev

**Additional context**
N/A

**Comment by atrievel** [comment]
I can tackle this issue if no one else is working on it

**Comment by pranesh-sp** [comment]
I shall take this up.

**Comment by jdkent** [comment]
@atrievel, you have precedence since you commented first on the issue, Thanks! Sorry @pranesh-sp, there are a couple other issue you can take on.

**Comment by pranesh-sp** [comment]
> @atrievel, you have precedence since you commented first on the issue, Thanks! Sorry @pranesh-sp, there are a couple other issue you can take on.

Thank you! I shall look at other issues.

**Comment by atrievel** [comment]
@jdkent To clarify: I should be replacing all of the headings and subheadings with `=====`, but does this include the subheadings that are already using `----` or should those be left as is?
