### ISSUE TITLE
2019 Society for Neuroscience Poster

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#241]
@PeerHerholz @tsalo @arokem @ctoroserey @kdestasio @rxqx @beckmart @RaginSagan @zkhan12 @snastase @pranesh-sp @njvack @kristianeschenburg @ipacheco-uy @ilkayisik @atrievel @KirstieJane 

Hi All, I am presenting a poster at [Society for Neuroscience](https://www.sfn.org/) in a couple weeks and I am using this software. I am letting everyone know in case they wish to opt-in for authorship. Leave a comment if you like to be listed as an author, or conditionally if you would like to see the poster first (with the knowledge I may not be able provide the poster in time).

**Feel free to ignore this message if you do not wish to be included as an author.**

While I will try to give you a poster you can provide feedback on/approve of, I cannot guarantee I will have time to incorporate your feedback. So if you decide to wish to be included as an author, you may be in a situation where you will not be able to provide feedback and/or I will not be able to incorporate the feedback.

Here is a [link to the abstract](https://www.abstractsonline.com/pp8/#!/7883/presentation/71026)

I apologize, but I am doing this too late to have you all listed as authors in the program, but I can have you on the physical poster.

Thank you for your contributions!

**Comment by tsalo** [comment]
It would be great to be included. Thank you!
