### ISSUE TITLE
add vizualizations of outputs

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#28]
Add visualizations of the connectivity matrix potentially as a circle graph with stronger connections between ROIs having thicker lines.

**Comment by PeerHerholz** [comment]
I played around with [mne's](https://martinos.org/mne/stable/index.html) [plot_connectivity_circle function](https://martinos.org/mne/stable/generated/mne.viz.plot_connectivity_circle.html#mne.viz.plot_connectivity_circle). Would be a visualization that works for everyone?
