### ISSUE TITLE
Output normalized betaseries

### ISSUE THREAD

**Issue by michaelmack** [HBClab/NiBetaSeries#281]
**Is your feature request related to a problem? Please describe.**
Estimating betaseries can result in poor fits and bizarre parameter estimates. These outlier estimates can then influence subsequent analyses. 

**Describe the solution you'd like**
One approach to dealing with this issue is to normalize the betaseries by the variance of the estimate. Adding this should be a fairly simple extension. In interfaces/nistats.py, could additionally calculate the effect variance and divide the beta_map by the variance:

`beta_var = model.compute_contrast(trial_type, output_type='effect_variance')`
`beta_mapn = beta_map/sqrt(beta_var)`

I'm actually not sure if the beta_map object can be directly used in the calculations like this, but that would be the idea. And these normalized betas could then be saved alongside the betaseries.

**Comment by jdkent** [comment]
Hi @michaelmack! thank you for raising this issue, and providing an example solution, I'll investigate this solution and give an update (hopefully by next week).

related #276

**Comment by jdkent** [comment]
follow up, if you pass `stat` to `compute_contrast`, you arrive at this [nistats code](https://github.com/nistats/nistats/blob/4ae4cd6b6cad1bfcc540678413e3d02a7cc7d3a6/nistats/contrasts.py#L184-L211) which is basically equivalent to your solution. I am about to merge a pull request that will slightly muddy the waters (#296), but I may just perform the same numerical procedure to combine the variances as I did with the beta estimates then divide the combined `beta_map` by the combined `sqrt` of the variance.

**Comment by michaelmack** [comment]
This sounds great!
