### ISSUE TITLE
Singularity build instructions wrong in docs

### ISSUE THREAD

**Issue by PeerHerholz** [HBClab/NiBetaSeries#287]
**Describe the bug**
The [singularity install instructions](https://nibetaseries.readthedocs.io/en/stable/installation.html#singularity-container) at the [installation page](https://nibetaseries.readthedocs.io/en/stable/installation.html) of the [nibetaseries docs](https://nibetaseries.readthedocs.io/en/stable/index.html) contain an error that prevents the correct build. In more detail the docs state that the following code should be run:
`singularity build /path/to/image/nibetaseries-vX.Y.Z.simg docker://HBClab/nibetaseries:vX.Y.Z`.

However, `docker repositories` should only contain lower case letters, hence `HBClab` should be changed to `hbclab` as in the [docker install instructions](https://nibetaseries.readthedocs.io/en/stable/installation.html#docker-container) for the build to work. 

**To Reproduce**
1. Try to build the nibetaseries Singularity image by running:
`singularity build /path/to/image/nibetaseries-vX.Y.Z.simg docker://HBClab/nibetaseries:vX.Y.Z`.
2. See error

**Expected behavior**
The nibetaseries Singularity Image should be build correctly. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.

**nibetaseries version**
v0.3.2.

**Comment by jdkent** [comment]
Hi @PeerHerholz, thanks for bringing this up, you've actually commented on this in #214, did you still want to take this on?

**Comment by PeerHerholz** [comment]
Hi @jdkent.

oh my, I'm so sorry, not sure how I missed this!
I'll close this and finally push the changes over there.
