### ISSUE TITLE
add zenodo

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#29]
for giving people accreditation for their contributions

**Comment by kdestasio** [comment]
Once you integrate Zenodo, you can add a link to the DOI in the repo documentation.

**Comment by jdkent** [comment]
awesome! Thanks so much for helping me irl. Did you want to submit a pull request to the readme? This should be what you need to add.

```
.. |zenodo| image:: https://zenodo.org/badge/95605121.svg
   :target: https://zenodo.org/badge/latestdoi/95605121
```
