### ISSUE TITLE
Error with dataset_description.json

### ISSUE THREAD

**Issue by mbpincus** [HBClab/NiBetaSeries#303]
Hello,

I'm trying to run Nibeta (0.5.0 version) and get the following error: "ValueError: Every valid BIDS-derivatives dataset must have a PipelineDescription.Name field set inside dataset_description.json."
I added this and tried to follow the BEP003 guidelines (which didn't give an example), but am getting the same error. I'm attaching a screenshot of the dataset_description.json file I'm using.

<img width="696" alt="Screen Shot 2020-04-01 at 2 45 35 PM" src="https://user-images.githubusercontent.com/17050542/78174740-beb06800-7427-11ea-8008-d35775f18b1c.png">

**nibetaseries version**
0.5.0 with Singularity image

**Comment by jdkent** [comment]
Hi @mbpincus,

That's not a great error message, but here is the [draft derivatives spec](https://bids-specification.readthedocs.io/en/derivatives/05-derivatives/01-introduction.html#derived-dataset-and-pipeline-description) that talks about the formatting, with the example copy/pasted below for convenience.   
```
{
    "Name": "FMRIPREP Outputs",
    "BIDSVersion": "TODO (depends when this PR will be merged)",
    "PipelineDescription": {
        "Name": "FMRIPREP",
        "Version": "1.2.5",
        "Container": {
            "Type": "docker",
            "Tag": "poldracklab/fmriprep:1.2.5"
            }
        },
    "SourceDatasets": [
        {
            "DOI": "10.18112/openneuro.ds000114.v1.0.1",
            "URL": "https://openneuro.org/datasets/ds000114/versions/1.0.1",
            "Version": "1.0.1"
        }
    ]
}
```

That should help you get past the error you are seeing.

**Comment by mbpincus** [comment]
Okay thanks so much! Another question about a new error I'm seeing.
The error message says:
"ValueError: could not find preprocessed outputs: {'subject' : 'S33107', 'datatype': 'func', 'suffix': 'bold', 'extension': ['nii', 'nii.gz'], 'scope' : 'derivatives', 'space': "MNI152Lin2009cAsym'

I'm wondering if the problem has to do with the space. I see on the Nibeta page that the default space is MNI152Lin2009cAsym. My output image is from fsl's feat and fsl says it's using the MNI 152 nonlinear 6th generation atlas. To be honest I'm not clear if this is same/different from the MNI152Lin2009cAsym, but my suspicion is that this could be the source of the problem. Could you provide any advice to help me troubleshoot this? I really appreciate it!

**Comment by jdkent** [comment]
Glad that got you past that error, for this one, you [should be able to specify](https://nibetaseries.readthedocs.io/en/stable/usage.html#Options%20for%20selecting%20images) `--space-label MNI152NLin6Asym` and get past that error

Curious from your reply, did you modify a FEAT directory to conform to the BIDS derivatives specification?

That may be the next step to get this working, since (at least the commandline usage) of nibetaseries depends on the BIDS derivatives organization to function properly.

**Comment by mbpincus** [comment]
Hello,

Thanks so much for your help with this. Please let me know if this is an appropriate place to be posting these questions, or if there's a different forum.

I attempted to modify a FEAT directory to confirm to the BIDS derivatives specification, not sure if I've entirely succeeded. My preproccessed subject files are called, for example, sub-S33107_ses-imaging_task-Stroop_space-MNI152_desc-preproc_bold.nii.gz. Because I called the space simply MNI152 in those files, I added the flag '--space-label MNI152' to the command and got it past the previous error. I now have a new error that says: "ValueError: The selected confounds contain nans: ['rot_x', 'rot_y', 'rot_z', 'trans_x', 'trans_y', 'trans_z']" I don't know why it's reporting that..?

**Here is my file organization/naming-scheme:**

BIDS/
    dataset_description.json
    sub-S33107/
        ses-imaging/
            anat/
                sub-S33107_ses-imaging_T1w.json
                sub-S33107_ses-imaging_T1w.nii.gz
            func/
                sub-S33107_ses-imaging_task-Stroop_bold.nii.gz
                sub-S33107_ses-imaging_task-Stroop_bold.json
                sub-S33107_ses-imaging_task-Stroop_events.tsv
    derivatives/
         fslfeat/
             dataset_description.json
             sub-S33107/
                 ses-imaging/
                     func/
                         sub-S33107_task-Stroop_space-MNI152_desc-preproc_bold.nii.gz
                         sub-001_task-Stroop_desc-confounds_regressors.tsv
                         sub-001_task-Stroop_space-MNI152_desc-brain_mask.nii.gz

**Here is the command I ran:**
singularity run —cleanenv -B /BIDS \
-B /nibeta \
-B /nibeta/work \
/bin/nibetaseries-v0.5.0.simg \
nibs -c rot_x rot_y rot_z trans_x trans_y trans_z \
--participant-label S33107 \
--session-label imaging \
-t Stroop \
-w /nibeta/work \
-a /nibeta/hips1_l_thr25_2mm.nii.gz \
-l /nibeta/atlas_lookup.tsv \
/BIDS \
/BIDS/derivatives/fslfeat \
/nibeta \
participant

Looking at the minimal dataset necessary to run nibs on the nibeta documentation, I'm not clear on a couple things:
-Are the things specified as optional for BIDS, but listed here, necessary for running nibeta? For example, a README and CHANGES file at the root level is listed for the minimal dataset necessary, but this is currently optional for BIDS. 
-There is a T1w.json at the root level, but I have it in my subject's folders--according to BIDS specification (or at least my read of it), either is fine--but for running nibeta, is it necessary for the T1w.json to be ONLY at the root level? 
-Does the task-stroop_events.json file represent a metadata file for the stroop task events? I was just looking back at the BIDS specification and it's unclear to me if that's the case, or if it represents an events file in the case of all participants having the same events. I find the BIDS documentation has gotten less clear since they migrated to a new format. 
-Is it necessary for the 'data' folder with the atlas nifti to be located directly inside the derivatives folder, as in the example of the minimal dataset necessary? I didn't note this requirement in the BIDS BEP003 extension proposal, but may have misunderstood.

Thank you so very much for your help and clarification and hope you are well in these corona times.

**Comment by jdkent** [comment]
Thanks for sharing your directory structure and command, that helps a ton.

>  I now have a new error that says: "ValueError: The selected confounds contain nans: ['rot_x', 'rot_y', 'rot_z', 'trans_x', 'trans_y', 'trans_z']" I don't know why it's reporting that..?

Could you share `sub-001_task-Stroop_desc-confounds_regressors.tsv`? (you can change the extension to `.txt` and drag and drop the file into this chat). I think that will give us the best clue on that error.
The other weird thing are these two files:
```
sub-001_task-Stroop_desc-confounds_regressors.tsv
sub-001_task-Stroop_space-MNI152_desc-brain_mask.nii.gz
```
should `sub-001` be `sub-S33107`?

> Are the things specified as optional for BIDS, but listed here, necessary for running nibeta? For example, a README and CHANGES file at the root level is listed for the minimal dataset necessary, but this is currently optional for BIDS.

README and CHANGES are not necessary, as long as it's a "valid" BIDS dataset, contains a `func` folder with at least one `_events.tsv` (and a `_bold.json` somewhere in the dataset, I will come back to this in your other question), this software should support that use case, if it does not, it is a bug.

> There is a T1w.json at the root level, but I have it in my subject's folders--according to BIDS specification (or at least my read of it), either is fine--but for running nibeta, is it necessary for the T1w.json to be ONLY at the root level?

The json file can be either at subject level or at root level, following the principles of BIDS, if an error can be traced to not reading the correct json file, that can be considered a bug in the software.

> Does the task-stroop_events.json file represent a metadata file for the stroop task events? I was just looking back at the BIDS specification and it's unclear to me if that's the case, or if it represents an events file in the case of all participants having the same events.

Yes, your first answer is correct, something like `task-stroop_events.json` should give a description of each of the columns in the `.tsv`, acting as metadata.

> I find the BIDS documentation has gotten less clear since they migrated to a new format.

you're talking about the [bids-specification website](https://bids-specification.readthedocs.io/en/stable/)? If that's the case, if you can expand on how site organization is hindering you finding what you need, then [they would certainly welcome the feedback](https://github.com/bids-standard/bids-specification/issues).

> Is it necessary for the 'data' folder with the atlas nifti to be located directly inside the derivatives folder, as in the example of the minimal dataset necessary? I didn't note this requirement in the BIDS BEP003 extension proposal, but may have misunderstood.

Nope, you are correct in not finding the requirement in BIDS BEP003. The location of the atlas nifti is  currently outside of the specification, so I have no expectations of where it should be.

Hope those answers help a bit.

**Comment by mbpincus** [comment]
You are incredibly helpful and I really appreciate it. I'm sharing the sub-S33107_task-Stroop_desc-confounds_regressors.txt file below.

Ignore the weirdness with sub-001, I copied/pasted the file names from the nibeta website because it was quicker than writing it out and I couldn't copy/paste from my server. What I'm really using is sub-S33107 and the command consistently reflected that when I submitted it on my server. Okay, thank you for all your other responses, that really clarifies things.

I don't have a metadata file for the tasks, so I will also work on that now and see if that alters the error message. I don't think I got flagged for that when I used the BIDS validator, which confuses me.

Thanks again!

[sub-S33107_ses-imaging_task-Stroop_desc-confounds_regressors.txt](https://github.com/HBClab/NiBetaSeries/files/4456817/sub-S33107_ses-imaging_task-Stroop_desc-confounds_regressors.txt)

**Comment by jdkent** [comment]
Thanks for sharing the `regressors` file, loading it in python gives the answer for nan error:
```
>>> import pandas as pd
>>> pd.read_csv("sub-S33107_ses-imaging_task-Stroop_desc-confounds_regressors.txt", sep='\t')
                                                 rot_x  rot_y  ...  trans_y  trans_z
0    0  0.000176422  5.85249e-05  0.000262852  0.04...    NaN  ...      NaN      NaN
1    -0.000224711  0.000298132  0.000665912  -0.018...    NaN  ...      NaN      NaN
2    0.000369195  0.000809932  0.00081096  -0.01693...    NaN  ...      NaN      NaN
3    0.000411723  0.000744615  0.000795755  -0.0300...    NaN  ...      NaN      NaN
4    0.000404916  0.000608084  0.00066129  -0.03072...    NaN  ...      NaN      NaN
..                                                 ...    ...  ...      ...      ...
399  -0.00319472  0.00265949  0.000745513  -0.04630...    NaN  ...      NaN      NaN
400  -0.00301684  0.00264092  0.000896295  -0.04338...    NaN  ...      NaN      NaN
401  -0.00326684  0.00273081  0.000847292  -0.04335...    NaN  ...      NaN      NaN
402  -0.00344425  0.00295634  0.000545997  -0.04321...    NaN  ...      NaN      NaN
403  -0.00325793  0.00289367  0.000514275  -0.03914...    NaN  ...      NaN      NaN

[404 rows x 6 columns]
```

It looks like all the fields are not entirely separated by tabs (they may be separated by a couple spaces or something similar, if you can replace the field separators to be all tabs, you should get past the nan error you are seeing.

**Comment by mbpincus** [comment]
Woof! That was a doozy to figure out the problem with that file but I finally got that fixed and moved past that error. now I have a new error, and it's complaining about a file being 4D when it's expecting a 3D file, but I'm not sure *which* file it's complaining about. Could you assist me in tracking down this error? I'm pasting a screenshot of the error below. Thanks so much! Be well in these here corona times.

<img width="1238" alt="Screen Shot 2020-04-13 at 4 14 47 PM" src="https://user-images.githubusercontent.com/17050542/79157477-a420ac00-7da2-11ea-92f2-eb295c17c2e3.png">

**Comment by jdkent** [comment]
Awesome you got the nans sorted!

This appears to be suggesting this file: `sub-S33107_task-Stroop_space-MNI152_desc-brain_mask.nii.gz` is 4D, while a mask _should_ be a 3d image.
I would check this with nibabel that installed through your singularity container, with a command that looks something like this:
```
singularity exec /bin/nibetaseries-v0.5.0.simg nib-ls /path/to/image/func/sub-S33107_task-Stroop_space-MNI152_desc-brain_mask.nii.gz
```

Which should output something like
```
/path/to/image/func/sub-S33107_task-Stroop_space-MNI152_desc-brain_mask.nii.gz float32 [ 64,  64,  37] 3.44x3.44x4.00
```

where `[ 64,  64,  37]` should only have three numbers (meaning three dimensions). If there are four numbers (e.g., `[ 64,  64,  37, 1]`), you will need to manipulate the image to make it three dimensions. If that is the issue, I can give some help on how to make the image 3D if you wish.

**Comment by mbpincus** [comment]
Okay, thanks so much. Figured that out too, the mask being made was 4D, so I extracted just the first volume and made it 3D. Now i've run into a new error, and I don't know what to make of it..?
THANK YOU! Pasting error below.

<img width="1084" alt="Screen Shot 2020-04-14 at 12 56 32 PM" src="https://user-images.githubusercontent.com/17050542/79252422-92e1a900-7e4f-11ea-84ab-5772b624df46.png">

**Comment by jdkent** [comment]
For this one could you attach the crash file specified in the line `Saving crash info to...`,

I suspect it has something to do with the atlas file, but I'm not positive.

As a potentially helpful question, is  `/nibeta/hips1_l_thr25_2mm.nii.gz` an image with several unique integers with corresponding entries in `/nibeta/atlas_lookup.tsv`?

**Comment by mbpincus** [comment]
Hello,

Okay, that question tipped me off to what was happening, and I resolved it. It runs to completion now!! Thank you!!

One last question (hopefully). I'm wondering if there's an option for censoring volumes. I saw a mention of censoring in the changelog, but don't see it mentioned in the usage section. Thanks so much!

Best,
Melanie

**Comment by jdkent** [comment]
That's great news!

As of v0.5.0, I [do censor volumes](https://github.com/HBClab/NiBetaSeries/blob/1667c8d3a761713604073e37b13ab15df4abd0c5/src/nibetaseries/interfaces/nilearn.py#L153-L190), but within the context of trying to get my dissertation written, I haven't had time to tidy up/update the documentation (and there is not a good way to tell what volumes have been censored, which really needs to be implemented). 

I'll bump the reporting of censored volumes higher to my todo list.

**Comment by jdkent** [comment]
Also, hope you too are doing well in these corona times.
