### ISSUE TITLE
Censoring incorrect trials and volumes with outliers

### ISSUE THREAD

**Issue by mbpincus** [HBClab/NiBetaSeries#311]
Hello again,

I'm wondering how you handle incorrect trials with nibeta modeling. I would ideally like to not include these trials in the beta-series analysis--is there an option to censor incorrect trials somehow? I do not currently have a trial_type for 'incorrect' in my task-events.tsv file. How do you handle this? I can modify the participant's task-events.tsv file to include 'incorrect' as a trial type, but am unclear if this is a common practice in creating task-events.tsv files.

You mentioned censoring volumes was possible (though it's not possible to report number of censored volumes). I looked through the code, but I wasn't able to deduce what flags would be added to the nibs command to automatically perform volume censoring. If you could provide that information here, I would be most appreciative!

**nibetaseries version**
0.5.0 with Singularity image

Thanks,
mbp

**Comment by jdkent** [comment]
Hi @mbpincus,

Censoring volumes that are largely deviant from the other volumes occurs automatically, without the specification of any additional options. (But note, this is only done for the correlation analysis, the beta series nifti images being returned contain all volumes, outliers and all).

To model incorrect trials separately, the current solution would be what you hinted at doing

> I do not currently have a trial_type for 'incorrect' in my task-events.tsv file. How do you handle this? I can modify the participant's task-events.tsv file to include 'incorrect' as a trial type, but am unclear if this is a common practice in creating task-events.tsv files.

I would change incorrect trials in the trial_type column to represent that they are incorrect.
I've done this for my own purposes, but I'm not on top of the [BIDS modelling specification](https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/edit) to say if this is "good practice".

Hope that helps!
James

**Comment by mbpincus** [comment]
Hey James,

Are you changing the trials to 'incorrect' in the task-events.tsv files in your participant's BIDS directory (because that's my understanding of where nibeta is pulling that from), rather than a 'simulacrum' folder. I was looking at neurostars questions and couldn't figure out if that's "acceptable practice" to include incorrect trials in the trial_type column of task-events.tsv file in the BIDS folder? I hear that you do not know if it's good practice for BIDS modeling specification, but that doesn't seem to apply here, unless I'm confused.

Okay, I imagine there would be no way for me to do censoring first outside of nibeta and have this work successfully because the modeling would not know how to align the imaging data and task data? 

Thank you so much. 
Melanie

**Comment by jdkent** [comment]
> Are you changing the trials to 'incorrect' in the task-events.tsv files in your participant's BIDS directory (because that's my understanding of where nibeta is pulling that from), rather than a 'simulacrum' folder. I was looking at neurostars questions and couldn't figure out if that's "acceptable practice" to include incorrect trials in the trial_type column of task-events.tsv file in the BIDS folder?

I would say changing the entries in the `trial_type` column of the `_events.tsv` to include information about incorrect trials is acceptable.

(e.g., changing `congruent` to `congruent_correct` and `congruent_incorrect` depending on participant response is acceptable to me and will generate two different beta series: one for `congruent_correct` and `congruent_incorrect`, assuming there are at least trials in each category, you will also get correlation matrices)

> Okay, I imagine there would be no way for me to do censoring first outside of nibeta and have this work successfully because the modeling would not know how to align the imaging data and task data?

This would be dubious to me and I would not recommend this strategy.

**Comment by mbpincus** [comment]
Ha ok! Thanks James. This has been so helpful.
