### ISSUE TITLE
Error about Directory Not Being Available 

### ISSUE THREAD

**Issue by mbpincus** [HBClab/NiBetaSeries#315]
I had to make a few changes to some BIDS and preprocessed files and wanted to make sure nibeta would still run okay. I entered in the same command as I had successfully used in the past, and the error is not verbose enough for me to understand what the problem is. 

Command:
singularity run --cleanenv -B /projects/vm430_1/MRLab/data/Decimals_Pilot/BIDS \
                          -B /projects/vm430_1/MRLab/data/Decimals_Pilot/derivatives/nibeta  \
                          -B /projects/vm430_1/MRLab/data/Decimals_Pilot/derivatives/nibeta/work \
                             /projects/vm430_1/MRLab/bin/nibetaseries-v0.5.0.simg \
                            nibs -c rot_x rot_y rot_z trans_x trans_y trans_z \
                                  --participant-label S33107 \
                                  --space-label MNI152 \
                                  --session-label imaging \
                                  --t Stroop \
                                   -w /projects/vm430_1/MRLab/data/Decimals_Pilot/derivatives/nibeta/work \
                                  -a /projects/vm430_1/MRLab/scripts/Decimals_Pilot/nibeta/hips_l_and_r_diff_labels.nii.gz \
                                  -l /projects/vm430_1/MRLab/scripts/Decimals_Pilot/nibeta/atlas_lookup.tsv \
                              /projects/vm430_1/MRLab/data/Decimals_Pilot/BIDS \
                              /projects/vm430_1/MRLab/data/Decimals_Pilot/derivatives/fslfeat \
                              /projects/vm430_1/MRLab/data/Decimals_Pilot/derivatives/nibeta \
                              participant

I'll paste the error below. The message complains the directory is not an available directory. I'm not sure what that means?  I've checked that I'm spelling out the path correctly.

<img width="795" alt="Screen Shot 2020-04-30 at 11 44 44 AM" src="https://user-images.githubusercontent.com/17050542/80730845-177f2900-8ad8-11ea-8087-c9c67515e8e4.png">

Thank you so much for your help!

**Comment by jdkent** [comment]
Looks like that directory is not available in the singularity container since it was not bound within it. if you use:
```
-B /projects/vm430_1/MRLab/data/Decimals_Pilot/derivatives
```
 in your singularity command, then `nibeta`, `nibeta/work`, and `fslfeat` should all be accessible from within your singularity container.

**Comment by mbpincus** [comment]
Hi James,

Hmm, the issue seemed to have resolved on its own when I tested the same command I used yesterday. Not sure what's going on with that but not going to question it.

Best,
Melanie
