### ISSUE TITLE
Question about trial_type

### ISSUE THREAD

**Issue by mbpincus** [HBClab/NiBetaSeries#316]
Hello,

For my task, the trial types in the BIDS events.tsv file have underscores in them in the trial_type column (for example, 'zero_consistent' and 'zero_inconsistent'). When I ran nibeta on data from this task, it seems to have collapsed across trials based on the string before the underscore (following the previous example, a betaseries for 'zero' trials only, not 'zero_consistent' and 'zero_inconsistent'.) I don't see a specification for the naming of trials in the trial_type column of the BIDS events files in the BIDS protocol. Can you give some more clarification on how these should be named so are appropriately identified by nibeta? Thanks so much!!
Melanie

**Comment by jdkent** [comment]
oh yeah, that isn't well documented, but I treat all entries in `trial_type` as a BIDs value in a BIDs key-value pair, for example this file: `sub-control01_task-nback_sbref.nii.gz`, `task-nback` is a key (`task`), value (`nback`) pair. The restrictions on the key-value pairs are that the values must be alpha-numeric (that is; they only contain letters/numbers), so to keep in line with that restriction, the name should be ` ZeroConsistent` and `ZeroInconsistent`, but I should add some documentation and an explicit check of the events file to catch such names.

**Comment by mbpincus** [comment]
Just to be clear, I'm referring to the names of the trial types *inside* the events file, not the naming convention for the events file itself. I was aware hyphens couldn't be in the task name (the value 'nback' in your example above), but you are saying they also cannot occur in the names of the trial types themselves, correct?

**Comment by jdkent** [comment]
That is true for my application, but I haven't yet gone through the process to propose adding that restriction to the BIDS standard.

**Comment by mbpincus** [comment]
Okay! Thank you for the clarification!
