### ISSUE TITLE
cannot pull nibetaseries

### ISSUE THREAD

**Issue by limbicode214** [HBClab/NiBetaSeries#317]
Hi there

I can't pull the image. Tried it on two different machines. 
"docker pull hbclab/nibetaseries" lead to an error:
"Could not reach any registry endpoint"

Does anyone have the same problem ? 

thanks, mike

**Comment by jdkent** [comment]
Hi Mike,

Sorry about the trouble, you need to specify a [version/tag you want to pull](https://nibetaseries.readthedocs.io/en/stable/installation.html#docker-container) (e.g., `docker pull hbclab/nibetaseries:v0.6.0`)

The default version/tag is `latest` which changes every time someone makes a change to the code, so the `latest` you use today probably won't be the same `latest` if you pull again a few months from now, making it difficult to know what version of the code you are running.

If you really need bleeding edge, there is also an `unstable` tag (buyer beware).

**Comment by limbicode214** [comment]
thanks! 
very useful tool!
