### ISSUE TITLE
Can nibetaseries run multiple sessions simultaneously?

### ISSUE THREAD

**Issue by LilianYou** [HBClab/NiBetaSeries#318]
Dear experts,

I am new to beta series analysis. My experiment has 6 sessions (Event-related design) so I have 6 nifti.gz files. I'm wondering if nibetaseries could run multiple sessions together or do I have to run one session at a time? The only tutorial example I could find ( https://github.com/HBClab/NiBetaSeries/blob/master/examples/plot_run_nibetaseries.py ) is only running one session so I am confused. Could you please point me in the right direction? 

Thanks,
Lily

**Comment by jdkent** [comment]
Hi Lily,

If you do not specify `--session-label` then by default nibetaseries should try to run on all sessions found, and in fact without `--participant-label` specified, nibetaseries will attempt to run for all participants within the bids dataset.

Best,
James

**Comment by LilianYou** [comment]
Thank you, James!
