### ISSUE TITLE
Error: dataset_description.json.

### ISSUE THREAD

**Issue by limbicode214** [HBClab/NiBetaSeries#321]
Hi guys

I am getting the error: 
"Every valid BIDS-derivatives dataset must have a PipelineDescription.Name field set inside dataset_description.json."

This is somewhat strange as I have a valid dataset_description file in my root derivatives folder: 
{
    "Name": "fMRIPrep - fMRI PREProcessing workflow",
    "BIDSVersion": "1.1.1",
    "PipelineDescription": {
        "Name": "fMRIPrep",
        "Version": "20.0.7",
        "CodeURL": "https://github.com/poldracklab/fmriprep/archive/20.0.7.tar.gz"
    },
    "CodeURL": "https://github.com/poldracklab/fmriprep",
    "HowToAcknowledge": "Please cite our paper (https://doi.org/10.1038/s41592-018-0235-4), and include the generated citation boilerplate within the Methods section of the text."
}

Thanks for help, mike

**Comment by jdkent** [comment]
Hi Mike,

That's a bit odd since at least what you've copy pasted here looks valid, could you attach the `dataset_description.json` file here (you may have to change the suffix to `.txt`) so I can see if I can replicate the error message?

Best,
James

**Comment by limbicode214** [comment]
James, many thanks. Attached is the file. 
[dataset_description.txt](https://github.com/HBClab/NiBetaSeries/files/4756936/dataset_description.txt)

**Comment by limbicode214** [comment]
Thanks a lot James for your help!
