### ISSUE TITLE
Crash File reporting KeyError: 'RepetitionTime'

### ISSUE THREAD

**Issue by mbpincus** [HBClab/NiBetaSeries#323]
Hello again!
I ran nibeta on data from a new study and got an error that repots KeyError: 'RepetitionTime', I'm not sure what to make of it? 
I'm attaching a screenshot below of the crash report and the command that I ran.
Thank you so much for your help interpreting this!

Best,
Melanie

Command:
singularity run —cleanenv -B /BIDS
-B /nibeta
-B /nibeta/work
/bin/nibetaseries-v0.5.0.simg
nibs -c rot_x rot_y rot_z trans_x trans_y trans_z
--participant-label 001
-t stroop
-w /nibeta/work
-a /nibeta/hips1_l_thr25_2mm.nii.gz
-l /nibeta/atlas_lookup.tsv
/BIDS
/BIDS/derivatives/fslfeat
/nibeta
participant

nibetaseries version 0.050 with singularity

<img width="1014" alt="Screen Shot 2020-06-11 at 4 28 42 PM" src="https://user-images.githubusercontent.com/17050542/84436240-183fca80-ac01-11ea-8d50-f937355b98a3.png">

**Comment by jdkent** [comment]
Hi @mbpincus, 

This error is similar #319, you can see the [relevant reply here](https://github.com/HBClab/NiBetaSeries/issues/319#issuecomment-638392942).

Hope that helps!
James

**Comment by mbpincus** [comment]
Yup that solved it. I was forgetting to copy the bold metadata json with the TR listed to the scratch folder where I do the processing. thanks!!!

**Comment by jdkent** [comment]
Awesome!
