### ISSUE TITLE
How to deal with event files from multiple runs?

### ISSUE THREAD

**Issue by LilianYou** [HBClab/NiBetaSeries#325]
Dear expert,

I'm trying to conduct beta series analyses for multiple runs simultaneously. I am a little confused about how should I manipulate the event file. The tutorial only deals with one event file from one run, but how should I deal with multiple event files from multiple runs (all saved in one folder)? Do I need to combine events from all runs in one data frame? If I save them separately, how should I name it? Here is a screenshot of manipulation of a single event file:

<img width="1105" alt="Screen Shot 2020-06-11 at 8 49 57 PM" src="https://user-images.githubusercontent.com/30990195/84462927-1ee03900-ac25-11ea-9bc4-31f35fde6c81.png">

Best,
Lily

**Comment by jdkent** [comment]
Hi Lily,

If you have two bold runs named

```
sub-033_task-boldRun1_run-1_bold.nii.gz
sub-033_task-boldRun1_run-2_bold.nii.gz
```

Then you would want two event files in the same directory named:
```
sub-033_task-boldRun1_run-1_events.tsv
sub-033_task-boldRun1_run-2_events.tsv
```

nibetaseries will attempt to run on all properly named files in the bids directory if no filters are specified.

Hope that helps!
James

**Comment by LilianYou** [comment]
Hi James,

Please let me clarify my question. I'm not asking about how to name tsv file, but how to name each dataframe extracted from tsv file instead. There is a step to read the tsv file and save it as a events_df dataframe (as the screenshot above). Is this step necessary? If yes, I'm wondering how to name that 'events_df' data frame from each event file? Such as events_df1, events_df2. 

Best,
Lily
