### ISSUE TITLE
update contributing guidelines

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#39]
Have the contributing guidlines follow what I actually want.

Inspirations:
- [fmriprep](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md)
- [STEMMRoleModels](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CONTRIBUTING.md)
- [tedana](https://github.com/ME-ICA/tedana/blob/master/CONTRIBUTING.md)

**Comment by KirstieJane** [comment]
I also really like the contributing guidelines from the [BIDS Starter Kit](https://github.com/INCF/BIDS-Starter-Kit/blob/master/CONTRIBUTING.md) - they have a lot of the STEMM Role Models stuff but they're pretty souped up!! 💪 ✨ 👾
