### ISSUE TITLE
fix links in readme.rst

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#54]
**Describe the bug**
The readme.rst has several links that are not rendering correctly in [restructured text](http://docutils.sourceforge.net/docs/user/rst/quickref.html)

**To Reproduce**
Look at the [readme](https://github.com/HBClab/NiBetaSeries/blob/master/README.rst)

**Expected behavior**
The words should be hyperlinks and not links next to the words

**Desktop (please complete the following information):**
N/A

**nibetaseries version**
N/A

**How to fix**
change the links in [this line](https://github.com/HBClab/NiBetaSeries/edit/master/README.rst#L97)
specifically:
`contributing <https://nibetaseries.readthedocs.io/en/latest/contributing.html>` becomes
`contributing <https://nibetaseries.readthedocs.io/en/latest/contributing.html>`_

and `issues <https://github.com/HBClab/NiBetaSeries/issues>` becomes
`issues <https://github.com/HBClab/NiBetaSeries/issues>`_

(you add an underscore at the end)

**Comment by janelleliu** [comment]
working on it
