### ISSUE TITLE
Clarify the issue number 'Fix' format in pull request

### ISSUE THREAD

**Issue by kdestasio** [HBClab/NiBetaSeries#58]
**Describe the bug**
It is not clear that the issue number needs to go next to 'Fix #' without a space in the text of a pull request.

**To Reproduce**
2. use option '...'
3. See error

**Expected behavior**
Add instructions to the pull request template that indicate the # and issue number are not separated by a space.

**Desktop (please complete the following information):**
n/a
**nibetaseries version**
Add the version of nibetaseries you are using
n/a
**Additional context**
n/a

**Comment by kristianeschenburg** [comment]
I'll look at this issue.

**Comment by jdkent** [comment]
Thanks for bringing up this issue @kdestasio! Would changing `Fixes # .` to `Fixes #<NUM>. (e.g. Fixes #58.)` clarify the template?
