### ISSUE TITLE
Add .zenodo.json

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#59]
**Is your feature request related to a problem? Please describe.**
since we've recently added zenodo, we should add the .zenodo.json file to track contributors over time.

**Describe the solution you'd like**
add a .zenodo.json like in [fmriprep](https://github.com/poldracklab/fmriprep/blob/master/.zenodo.json)

**Describe alternatives you've considered**
There are no alternatives :smiling_imp: 

**Additional context**
here will be my entry in the `.zenodo.json` file:
```
 {
      "name": "Kent, James D.",
      "affiliation": "Neuroscience Program, University of Iowa",
      "orcid": "0000-0002-4892-2659"
    },
```

**Comment by danielmlow** [comment]
This is a great idea. I'll work on it.

**Comment by jdkent** [comment]
Yes, this is still open if you wish to work on it :), I'll give @danielmlow one more day in case he still wants dibs.

**Comment by danielmlow** [comment]
Hi James,

Sorry, I was on a retreat. I'll hand it over to Claudio.

Best!
Dan

**Comment by jdkent** [comment]
Thanks for the reply Dan! 

There we have it, @ctoroserey, you can tackle this problem.

**Comment by ctoroserey** [comment]
Sounds good, on it!
