### ISSUE TITLE
pybids layout indexing takes too long

### ISSUE THREAD

**Issue by jdkent** [HBClab/NiBetaSeries#68]
**Describe the bug**
When indexing the dataset, a vanilla call to pypids can take over a half hour.

**To Reproduce**
Have a BIDS dataset with a sourcedata folder that contains individual dicoms (100,000s of files)

**Expected behavior**
The dataset should be indexed in a reasonable amount of time

**Desktop (please complete the following information):**
N/A

**nibetaseries version**
N/A

**Additional context**
N/A

**Comment by KirstieJane** [comment]
@jdkent - is this a pybids problem? Should *it* be ignoring the sourcedata dir? Or just an implementation error here?

**Comment by KirstieJane** [comment]
Oh nevermind - sorry - I just checked #69. All fixed :sparkles:
